Code of conduct
ProtoRedux/ProtoRedux.github.io pull request #8
Opened 2020-11-30 09:46 UTC by dylangrimes1

review of code of conduct

2020-12-02 21:56 UTC, DannyENL commented on codeofconduct
> +<p>2.	All deadlines must be completed in time, If there is any reason preventing a staff member completing a deadline, they must talk to their employer in advance to discuss extensions.</p>
I would change "in time, " to "on time. "

2020-12-02 21:59 UTC, DannyENL commented on codeofconduct
> +<p>5.	The use of computers to harass or discriminate against another person virtually or anonymously will be investigated </p>
Missing full stop

2020-12-02 21:59 UTC, DannyENL commented on codeofconduct
> +<p>7.	Every member of staff must show up to their scheduled hours, if for whatever reason someone cannot attend, they must discuss that with their employer in advance</p>
Missing full stop

2020-12-02 22:01 UTC, DannyENL commented on codeofconduct
> +<p>3.	Harassment towards any member of staff will not be tolerated, the workplace environment must be safe for all staff members, physical and verbal harassment is taken very seriously</p>
I would change "not be tolerated, the workplace environment", to "not be tolerated. The workplace environment". I would also change "members, physical" to "members; physical".

2020-12-02 22:01 UTC, DannyENL commented on codeofconduct
> +<p>4.	Discrimination, such as sexism, racism, ableism or homophobia will be taken very seriously and will be looked at individually depending on what happened</p>
Missing full stop

2020-12-02 22:04 UTC, DannyENL requested changes
The file doesn't have a html extension, which I think it'll need in order to be part of the website.
A few of the sentences don't end in full stops and certain sentences seem to run on for a while. I put in some suggestions for where a long sentence could be split up to make it a bit easier to read.

2020-12-07 12:44 UTC, ProtoRedux commented
Gonna close this pull request cause the changes are included in the latest code of conduct pull request.

2020-12-07 12:44 UTC, closed without merging